spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Argentina/Buenos_Aires&createDatabaseIfNotExist=true
    username: root
    password: root